### ISSUE TITLE
 Создать meetup.com группу чтобы все сообщества Camunda были в одном месте

### ISSUE THREAD

**Issue by huksley** [camunda-user-group-ru/camunda-user-group-ru.github.io#4]
Это не мешает фактические события хостить у спонсоров (делаем копию события)

Далее можно будет сделать ссылку на https://camunda.com/events/meetups/

**Comment by TitanUser** [comment]
Так же задал вопрос Луке. Ждем ответа.

**Comment by huksley** [comment]
https://www.meetup.com/Camunda-User-Group-Russia/
